### ISSUE TITLE
Support OpenTracing-2.0.0

### ISSUE THREAD

**Issue by prometheanfire** [jaegertracing/jaeger-client-python#199]
## Requirement - what kind of business use case are you trying to solve?

Update requirements for the openstack/requirements project

## Problem - what in Jaeger blocks you from solving the requirement?

https://github.com/jaegertracing/jaeger-client-python/blob/master/setup.py#L42
Specifically the cap on opentracing.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Update jaeger-client to work with opentracing-2 as well.

**Comment by mihau** [comment]
I've created a WIP pull request that bumps `opentracing` to 2.0 #206

**Comment by bentsi** [comment]
Unable to use start_active_span in tutorial https://github.com/yurishkuro/opentracing-tutorial/tree/master/python/lesson02
When opentracing 2.0 support will be added to the jaeger python client?

**Comment by denisdubovitskiy** [comment]
Is there any chance for this PR to be merged? There is already 3rd version of opentracing released. This issue looks abandoned

**Comment by yurishkuro** [comment]
apologies for delays, we're short staffed these days due to higher priority projects, and this is a breaking change, so requires a lot more attention / effort than just a code review.

**Comment by mjgorman** [comment]
Just throwing a +1 here. We were getting ready to start an implementation and this may delay us given the changes.

**Comment by tvfoodmaps** [comment]
Is this issue the reason I get:

```
  File "/usr/local/lib/python3.7/site-packages/opentracing/tracer.py", line 126, in start_active_span
    return self._noop_scope
AttributeError: 'Tracer' object has no attribute '_noop_scope'
```

When I try to install both Flask-Opentracing and jaeger-clent I get:

`jaeger-client 3.13.0 has requirement opentracing<2,>=1.2.2, but you'll have opentracing 2.0.0 which is incompatible`

**Comment by vinhlh** [comment]
+1

**Comment by nicholasamorim** [comment]
+1

**Comment by nicholasamorim** [comment]
The last merges brok the OT2.0 PR, #206.

@yurishkuro @mihau Is there any way I could contribute to get this merged?

**Comment by prometheanfire** [comment]
Ya, it would be nice to have some movement on this, get a release supporting opentracing-2 before we tag our bi-yearly releases.

**Comment by yurishkuro** [comment]
I'm almost done with my book, will get to these in March.

**Comment by tvvignesh** [comment]
Eagerly awaiting this release. Currently we are working with v1.3.0 of OpenTracing, not sure how many breaking changes would come in to the code after the upgrade.

**Comment by nicholasamorim** [comment]
Sorry to ask, but is this moving forward or will this project be relatively unmaintained for the time being? We were considering using Jaeger but the fact that the client doesn't get to OT2.0 and Tornado>5 is a fairly big showstopper at the moment.

**Comment by yurishkuro** [comment]
I'm planning to finish it this weekend

**Comment by r0fls** [comment]
Is there a way to use the jaeger client python right now before this release is made? When using it with https://github.com/opentracing-contrib/python-flask it seems they both require incompatible versions of opentracing. Is there a release combination that works together right now?

**Comment by yurishkuro** [comment]
I used a temporary branch in my book:

https://github.com/PacktPublishing/Mastering-Distributed-Tracing/blob/fb83d0766face96fc5b0a2b9485ffd3c3fd62743/Chapter04/python/requirements.txt#L10

**Comment by mihau** [comment]
I updated my pull request, the code seems to work fine. I'm using it successfully with gevent scope manager. @yurishkuro let me know if there is anything I can help with regarding this issue, I should manage to find some time to do any necessary fixes this week.

**Comment by r0fls** [comment]
I get this error when I try to use the forked version:

```
  Running setup.py develop for jaeger-client
    ERROR: Complete output from command /home/raphael/code/turquoise/venv/bin/python3 -c 'import setuptools, tokenize;__file__='"'"'/home/raphael/code/turquoise/venv/src/jaeger-client/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --home=/tmp/pip-target-j21cgri3:
    ERROR: usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --home not recognized
```

**Comment by tvvignesh** [comment]
@yurishkuro Just noticed the upgrade. Thanks. Any API changes to Jaeger client? Or will my old code still work?

**Comment by yurishkuro** [comment]
I did an experiment in our internal test bed and it worked fine without changes. But this release introduces built-in context propagation (via Scope Managers).

**Comment by prometheanfire** [comment]
so, it's been over a year now...

**Comment by yurishkuro** [comment]
@prometheanfire what are you referring to? Support for OT 2.x was released in Jaeger 4.x https://github.com/jaegertracing/jaeger-client-python/blob/master/CHANGELOG.rst#400-2019-04-27
